### ISSUE TITLE
IntelliJ console

### ISSUE THREAD

**Issue by pliu** [mattn/go-isatty#12]
Although the windows IsTerminal correctly detected when it is in a Windows terminal, it doesn't detect if it is in an IntelliJ terminal. Would this be possible to add? I honestly have no idea :(

Thanks!

**Comment by mattn** [comment]
Try to get Fd from os.Open("CONOUT$")

**Comment by pliu** [comment]
Cool! Thanks. BTW, as a beginner, how does one know about these environment variables (i.e.: CONOUT)?

**Comment by mattn** [comment]
Hmm, I don't know. :/ Google? GitHub?

**Comment by pliu** [comment]
Definitely tried Googling to find out how to check for IntelliJ's terminal, lol. But got nothing :(

**Comment by mattn** [comment]
https://msdn.microsoft.com/en-US/library/windows/desktop/ms683231(v=vs.85).aspx ?

**Comment by pliu** [comment]
Oh cool! Thanks :)
