### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by cswank** [mattn/go-isatty#18]
Hi, I'm trying to use the new github.com/golang/dep tool for vendoring in a new project.  When I do it grabs 

```
{
            "name": "github.com/mattn/go-isatty",
            "version": "v0.0.1",
            "revision": "3a115632dcd687f9c8cd01679c83a06a0e21c1f3",
            "packages": [
                "."
            ]
        },
```

But the dep that triggered go-isatty as a dep (github.com/fatih/color) requires isatty.IsCygwinTerminal, which is in master.

```
go run main.go
# github.com/cswank/kcli/vendor/github.com/fatih/color
vendor/github.com/fatih/color/color.go:21: undefined: isatty.IsCygwinTerminal
```

Do you think you could create a new release?  The dep tool is pretty new and I'm not clear how I'd get around this otherwise.

**Comment by cswank** [comment]
I was able to get around it by doing:

`dep ensure -override github.com/mattn/go-isatty`

then editing manifest.json 

```
"overrides": {
        "github.com/mattn/go-isatty": {
            "branch": "master"
        }
    }

```
then 

`dep ensure -update`

However, a new release would still be nice.

**Comment by mattn** [comment]
tagged v0.0.2

Thanks.
