### ISSUE TITLE
Add NetBSD support to go-isatty

### ISSUE THREAD

**Issue by iamleot** [mattn/go-isatty#2]
Hello Yasuhiro and all go-isatty users,
today I have updated to the latest
[odeke-em/drive](https://github.com/odeke-em/drive) version and I saw
that go-isatty does not support NetBSD.
In order to add the support to it please just add `netbsd` in
`isatty_bsd.go`.

I have tested this change in NetBSD-current and pkgsrc-current (lang/go
version is 1.4.2) and I can confirm that now go-isatty works correctly.

Thank you for your attention!
Ciao,
L.

**Comment by mattn** [comment]
Thanks.
