### ISSUE TITLE
How does this differ from x/crypto/ssh/terminal.IsTerminal?

### ISSUE THREAD

**Issue by kevinburke** [mattn/go-isatty#21]
There is also a "is it a terminal" detector in this repository:  https://godoc.org/golang.org/x/crypto/ssh/terminal#IsTerminal

Does this package differ from that one in a significant way?

**Comment by mattn** [comment]
crypto/ssh is bits large for just checking isatty. And it's not build-safe on appengine. go-isatty have a function to check the terminal is cygwin/msys2.
