### ISSUE TITLE
Interactive mode or not

### ISSUE THREAD

**Issue by stantonxu** [mattn/go-isatty#24]
This is a feature request. Is it possible to determine if the go code is running in interactive mode or not? So that we can decide if we need to use the options / flag or interactive with end user for options.

**Comment by mattn** [comment]
What do you mean `interactive` ?

**Comment by stantonxu** [comment]
A real example is, I used Cobra/Viper to build a command line program, it has something like `program delete` command that you can type on console. By default, it will prompt question on console to confirm, or user can use `-f` or `--force` to delete it without prompt. 

But when this `program delete` is being called in shell script, I would like to it to be deleted by default without the prompt and without the `-f` or `--force` to be specifically typed, as I've already had other developer use `program delete` in the their scripts, and I don't want to break all those script.

So I hope I can detect if my program is typed in console or is called in script.

**Comment by mattn** [comment]
It's not depend who the app is spawned from.

```go
package main

import (
        "fmt"
        "os"

        "github.com/mattn/go-isatty"
)

func main() {
        if isatty.IsTerminal(os.Stdout.Fd()) {
                fmt.Println("You are in terminal")
        } else {
                fmt.Println("You are not in terminal")
        }
}
```

```
$ go build -o myapp main.go
```

```
#!/bin/sh
./myapp
```

You should be possible to see "You are in terminal".

**Comment by stantonxu** [comment]
That's right. That's not what I am looking for. For the reason I raised, I am expecting to see "You are not in terminal" in this case, or you are non-interactive.

**Comment by mattn** [comment]
Do you want the way to know whether parent process is shell?

**Comment by stantonxu** [comment]
I understand it is not an issue of go-isatty, I asked for it as feature request.

Actually, in my example, it is not the parent process is shell or not, it is about whether it is interactive with end user, or called silence in script.

**Comment by kolypto** [comment]
To find out whether the app is in interactive mode or not (e.g. in shell pipeline) , use `os.Stdin.Fd()` instead:

```go
	if isatty.IsTerminal(os.Stdin.Fd()){
		fmt.Fprintln(os.Stderr, "Reading from stdin. Press Ctrl-D to finish.")
	}
```

This works because it checks whether `os.Stdin` is *connected* to an interactive terminal -- which is false when the command is part of a pipeline.

When you use `os.Stdout` for checking interactiveness, you actually check whether `os.Stdout` is *connected* to an interactive terminal, which may hold true even when the command is in a pipeline.
