### ISSUE TITLE
Terminal is not detected when redirecting the output from the shell

### ISSUE THREAD

**Issue by asticode** [mattn/go-isatty#38]
When executing a golang app while redirecting the output from the shell (`./app > /tmp/my.log`), `IsTerminal()` returns `false` even though the app is run from a terminal. Is there any reason for that?

**Comment by mattn** [comment]
Because you are passing the file descriptor of stdout to IsTerminal(). If you want to check the pty, you must pass the file descriptor of pty.

**Comment by asticode** [comment]
Haaa it makes sense! Do you know if there's a way to get the file descriptor of the current pty in GO? [This repo](https://github.com/kr/pty) doesn't seem to do the trick and I can't think of a simpler solution.

**Comment by mattn** [comment]
What do you want to check with go-isatty? Please explain your use case?

**Comment by asticode** [comment]
For log purposes, I want to determine whether the app is executed in a terminal or not. If the app is executed in a terminal, I'll print the log on StdOut; if not, I'll print the log in Syslog. If my golang binary is located at `/path/to/binary`, running `/path/to/binary` in my shell works well and prints logs in StdOut. But running `/path/to/binary > /tmp/redirected.log` in order to redirect StdOut to a file, fails to detect the context as running in a terminal and therefore the logs are redirected to Syslog. Does that make more sense?

**Comment by mattn** [comment]
Probably, you have misunderstanding about "running on terminal". See https://github.com/mattn/go-isatty/issues/24

**Comment by asticode** [comment]
You are right.

For those who were misunderstanding things like me, here's what I ended up doing : I relied on `Stdin` instead of `Stdout`.

That way, whether running `./app` or `./app > /path/to/file`, `IsTerminal(os.Stdin.Fd())` always returns `true` but when executing the app in a non-interactive fashion, it returns false.
