### ISSUE TITLE
undefined: unix.IoctlGetTermios

### ISSUE THREAD

**Issue by Ramzec** [mattn/go-isatty#53]
I'm trying to build a project that uses "golang:1.13.10-alpine" docker image inside of Amazon-kubernetes enviroment, but there is an error:

vendor/github.com/mattn/go-isatty/isatty_tcgets.go:10:12: undefined: unix.IoctlGetTermios

Any thoughts?

**Comment by mason-jones-ck** [comment]
I just ran into this as well, but given that this issue is over a year old, I'm guessing perhaps the project is dead?

**Comment by mattn** [comment]
This cause is that x/sys/unix was not support alpine but now support it. So I'll update dependencies in later.

**Comment by mattn** [comment]
Hmm. build tag in x/sys/unix is 

```
// +build aix darwin dragonfly freebsd linux netbsd openbsd solaris
```

golang-alpine is Linux. So you should be possible to build. I don't understand why this occured.

**Comment by mason-jones-ck** [comment]
Interesting -- apparently it's possible for versions to get out of sync. This was on my MacBook. I did the following:
```
cd $GOPATH/src/golang.org/x
rm -rf sys
go get github.com/mattn/go-isatty
```
and it worked! There was apparently something unexpected/missing in the sys package?? Removing it forced a re-fetch when I installed your package, I assume, which fixed whatever was wrong.

**Comment by mattn** [comment]
So this seems not a problem of go-isatty. I'll close this. Please file new issue if you still have problems. Thanks.
