### ISSUE TITLE
macOS reports `true` for stdin?

### ISSUE THREAD

**Issue by gabyx** [mattn/go-isatty#55]
Do you know why:

```
package main

import (
	"fmt"
	"os"

	"github.com/mattn/go-isatty"
)

func main() {
	if isatty.IsTerminal(os.Stdin.Fd()) {
		fmt.Println("Is Terminal")
	}
}

```
is true when I run the executable by redirecting the stdout to a file like: `echo "asd" | ./app` 

Thanks for the help?

**Comment by bl-ue** [comment]
@gabyx I can't reproduce.  Are you sure that was the program you were running?

What macOS version / Go version are you running? Mine are macOS 11.1 and Go 1.15.5.
```console
$ ls
app.go
$ cat app.go
package main

import (
	"fmt"
	"github.com/mattn/go-isatty"
	"os"
)

func main() {
	if isatty.IsTerminal(os.Stdout.Fd()) {
		fmt.Println("Is Terminal")
	}
}

$ go build
$ ls
app	app.go
$ ./app
Is Terminal
$ ./app 1> LOG
$ ls
LOG	app	app.go
$ cat LOG
$

```

**Comment by gabyx** [comment]
I cant reproduce it either, strange. I really had this error. 
I will close it in a moment.

**Comment by gabyx** [comment]
No it was with `Stdin?

**Comment by gabyx** [comment]
Can you try again.

**Comment by gabyx** [comment]
OK cant reproduce. Prorbably mistaken somethiing. If it happens again. I report back. Thx for your time!
