### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by mislav** [mattn/go-isatty#6]
Hi, thanks for this great project!

Could go-isatty have an open-source license so that we may include, distribute, and modify this project?

Thanks!

**Comment by mattn** [comment]
As far as I can see, it is here.
https://github.com/mattn/go-isatty/blob/master/LICENSE

**Comment by mislav** [comment]
Thanks! I must have been looking at the source directory for the wrong project (go-colorable) when I opened this issue!

Sorry for the noise.

**Comment by mattn** [comment]
NP :)
