### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [mattn/go-isatty#7]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for go-isatty and versioning would help Debian keep up with development.

**Comment by mattn** [comment]
okay, done.

https://github.com/mattn/go-isatty/tree/v0.0.1

**Comment by mattn** [comment]
BTW, thanks for your work about debian package!

**Comment by aviau** [comment]
Thank you for this! Please make sure you keep tagging as you release new features and fix bugs.
