### ISSUE TITLE
Compatibility with newer golang.org/x/sys/unix

### ISSUE THREAD

**Issue by repli2dev** [mattn/go-isatty#77]
When using this package (as a dependency of getsentry 0.15) with `golang.org/x/sys/unix` a `golangci-lint` returns following error

```
[/go/pkg/mod/github.com/mattn/go-isatty@v0.0.16/isatty_tcgets.go:7:8: could not import golang.org/x/sys/unix (/go/pkg/mod/golang.org/x/sys@v0.0.0-20220928140112-f11e5e49a4ec/unix/syscall.go:83:23: Slice not declared by package unsafe)
```

Go 1.17

**Comment by dolmen** [comment]
@repli2dev Suggestion: try upgrading `golangci-lint`, preferably from source (`go install`) to be sure it matches your Go toolchain.

**Comment by dolmen** [comment]
#82 is related.

**Comment by dolmen** [comment]
golang.org/x/sys has been upgraded in #82.
