### ISSUE TITLE
Go-isatty Error with  EgeBalci/HERCULES 

### ISSUE THREAD

**Issue by cacaocaca** [mattn/go-isatty#9]
root@kali:~/Scrivania/HERCULES/SOURCE# go run HERCULES.go 
/usr/local/go/src/github.com/fatih/color/color.go:10:2: no buildable Go source files in /usr/local/go/src/github.com/mattn/go-isatty
How i can solve it ?

**Comment by mattn** [comment]
what is your OS?

**Comment by cacaocaca** [comment]
kali linux rolling but maybe i forget to install isatty maybe .. first i have many error for run hercules you dont image .. always find my the patch for https://github.com/fatih/color and go-isatty and on kali linxu is on /usr/local/go/src/github.com/ at the end i have run hercules clean thanks for your support the same i m so happy for your suppor bro .. Good day and good work ;)

**Comment by mattn** [comment]
NP
